### ISSUE TITLE
Menu is hidden when right-clicking at the bottom of the window

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo_gui#373]
As reported by @jgosmann in #342. Looks like this:

![screen shot 2015-06-09 at 2 58 43 pm](https://cloud.githubusercontent.com/assets/203709/8067067/48e5f82a-0eb9-11e5-8a34-ee66318f2898.png)

**Comment by cchan987** [comment]
In the cases where it is currently hidden at the bottom, should we have the menu appear so that its bottom corner is at the right clicked point? An alternative is to simply shift the menu up until the whole menu is shown, (which would mean the cursor is not necessarily on a menu corner)

**Comment by s72sue** [comment]
I think its more intuitive to have the cursor on a menu corner since you
expect the menu to show up somewhere close to the cursor. Having the menu
appear so that its bottom right corner is at the right clicked point would
work if the plot is on the right side of the screen but if the plot is on
the left end of the screen, then maybe the menu should appear so that its
bottom left corner is at the right clicked point.

-Sue

**Comment by tcstewar** [comment]
We should be consistent with what the normal browser right-click menu does.  As far as I can tell, here is the behaviour:

- it normally appears with the mouse cursor and the top-left corner.
- if this would take it off the right edge, move the menu to the left just enough so that it rests against the right-hand edge (so the mouse cursor is somewhere in the middle of the top)
- if this would take it off the bottom edge, move the menu all the way up by its full height(so the mouse cursor is at the bottom of the menu)

This seems to be consistent across Firefox and Chrome for me.....

**Comment by s72sue** [comment]
I agree, that's the right thing to do.

**Comment by cchan987** [comment]
> This seems to be consistent across Firefox and Chrome for me.....

Chrome for me (on linux) enforces that the menu appears with the cursor in a corner, alternating between the four corners depending on position.
