### ISSUE TITLE
Auto-detect used port

### ISSUE THREAD

**Issue by xchoo** [nengo/nengo_gui#374]
It would be nice if the server could assign an alternate port (and pop up the webpage linking to said port) if it detects that the default port is being used. I just tried with ipython notebook, and if the default port is being used (port 8888), it opens up the server on the next available port (port 8889).

**Comment by cchan987** [comment]
> if the default port is being used (port 8888)

Is the default port not 8080?

**Comment by jgosmann** [comment]
> Is the default port not 8080?

for nengo_gui, not for IPython notebook

It is also possible to have the OS chose some random available port by setting the port to 0. This is used for the IPython visualization. But I think, for a server started the normal way, predictable port numbers are better because it makes easier to manually navigate to the webpage (which is not really required in the IPython notebook).

**Comment by xchoo** [comment]
In the context of nengo_gui. If the default port is not being used, then connecting to 8080 will be just fine. Also, I'm not sure how often people will manually connect to the server. After all, if the server detects no running instances of the vizualizer, it shuts itself off. :smile_cat:

**Comment by jgosmann** [comment]
Another reason to not wildly vary the ports in normal server mode: It would somewhat mess up the users navigation history and the browser autocomplete when typing `localhost...` will show a lot of uninteresting entries.

**Comment by jgosmann** [comment]
Fixed in #865 (except for Windows).
