### ISSUE TITLE
Intercepts out of range have non-obvious consequences

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_gui#392]
(This might be more of a Nengo thing, but) If you set intercepts using Uniform(.95,1.5) and have only on neurons, the resulting tuning curves go across the entire range towards negative values.  We should probably tell the user there is a problem with the chosen dist or something rather than return off neurons.

**Comment by tbekolay** [comment]
Yeah, this is definitely a Nengo thing. Mind opening an issue there? Seems like we should raise a warning or something if a given `abs(intercept) > 1`. Or `abs(intercept) > radius`? I forget is we divide by radius...

**Comment by tcstewar** [comment]
Hmm...  I can think of situations where I'd like to have a radius < -1.  That'd just be a neuron that never turns off completely, but still fires at different rates for different x values..

**Comment by tbekolay** [comment]
Sorry, I was just not remembering if our intercept is defined in absolute terms (i.e., across `-5, 5` if radius is 5`) or relative (i.e., always -1 to 1, and gets scaled according to the radius). Basically, we just want to detect if choosing a particular intercept means that you encoder effectively gets flipped (because trying to satisfy the equations for gain and bias will give you a negative gain).

**Comment by tcstewar** [comment]
Ah, I see...   Hmm, I think that means we want to raise a warning for ```intercepts > 1``` (intercepts are scaled by radius, so that check will work for all radius values).  Having intercepts < -1 doesn't hit this problem.  And if we give a warning we should probably also set those neurons to gain=0 bias=0 or something like that.

**Comment by tcstewar** [comment]
This discussion is now over here: https://github.com/nengo/nengo/issues/1212

**Comment by jgosmann** [comment]
More detailed explanation about what valid intercepts are: https://github.com/nengo/nengo/pull/1243#issuecomment-267787806
There is a PR for nengo solving this issue nengo/nengo#1248 (anyone volunteering as second reviewer?)
