### ISSUE TITLE
Refactor server

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#456]
The server code is somewhat convoluted and it's hard to figure out which class takes responsibility to manage certain threads. This should be refactored to have a clear hierarchy. A potential problem in this might be that `BaseHTTPServer` was probably never intended to be used with persistent WebSocket connections.

**Comment by cchan987** [comment]
was this addressed as part of #460

**Comment by tcstewar** [comment]
Nope, this is about refactoring server.py and swi.py

**Comment by jgosmann** [comment]
Do we want this in the 0.2 release or should it wait for 0.3? The server code seems to be stable enough at the moment and the refactoring would have no user-facing changes.

If we want it for 0.2, I might start with it soon-ish.

**Comment by tcstewar** [comment]
That's a good point...  There really isn't a pressing need for it to go into 0.2, and I think focusing on the other changes would be a better use of time.

**Comment by Seanny123** [comment]
I know this isn't a huge priority right now, but since I'm building the documentation anyways, is there a specific library that you would consider useful?

Do you want to build something from scratch using [SocketServer](https://docs.python.org/2/library/socketserver.html) as seen in [this Gist](https://gist.github.com/jkp/3136208)? Alternatively, would you prefer using some sort of generic library like either:

- [websockets](https://pypi.python.org/pypi/websockets)
- [simple-websocket-server](https://github.com/dpallot/simple-websocket-server) which certainly seems to be the simplest, since it only has one file
- [python-websocket-server](https://github.com/Pithikos/python-websocket-server)

**Comment by jgosmann** [comment]
I can't answer the question at this point. I still have to evaluate what a good class structure with clear responsibilities would be and if this can be realized with the Python standard libraries.
