### ISSUE TITLE
Zooming with mouse pointer over plot or slider has wrong behaviour

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#470]
The zooming isn't centered on the mouse pointer in this case.

**Comment by cchan987** [comment]
odd i'm not getting the behaviour from yesterday. 
Was anyone able to replicate this on a different computer from Jan's?

**Comment by jgosmann** [comment]
Yes, I have the same behaviour on my desktop.

**Comment by tcstewar** [comment]
> Was anyone able to replicate this on a different computer from Jan's?

It's also replicated for me.  That said, it's a much more subtle effect than we were seeing on Jan's computer -- maybe off by a few pixels, but it's definitely there and only there when the mouse is over a graph/slider.

**Comment by cchan987** [comment]
The root of this issue is the use of layerX and layerY on line 153 of netgraph.js
This property has different meanings if it is triggered inside or outside of an element.
https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/layerX

Switched to Clientx and ClientY as they have appropriate behaviour inside and outside components

**Comment by tcstewar** [comment]
This should be fixed now by #496
