### ISSUE TITLE
Should SP data be sent as binary?

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#506]
In `value.py` the data for the lines is sent as binary. In contrast, `pointer.py` sends the lines as Python string. Is there a reason for this discrepancy or should one of them be adapted?

**Comment by tcstewar** [comment]
> In value.py the data for the lines is sent as binary. In contrast, pointer.py sends the lines as Python string. Is there a reason for this discrepancy or should one of them be adapted?

It's much simpler to send as a string, since that easily handles dealing with newly defined semantic pointer terms.  If you send it as binary data, you also need a separate way of sending information about what the text label is for each entry, and how many entries there are.  So I went with the string approach as it's nice and simple.  (Notice that ```value.py``` plots don't have to deal with suddenly changing the number of lines while the plot is running, so they can get away with the very simple binary approach).
