### ISSUE TITLE
Nengo_gui not finding numpy

### ISSUE THREAD

**Issue by ikajic** [nengo/nengo_gui#575]
I've installed `nengo` and `nengo_gui` from source, and running `nengo_gui ` in a command line gives me an error that `numpy` can't be found. Calling `nengo_gui` in a script works fine though.

The error:

```
(nengo-dev)ivana@CTN05:~/src$ nengo_gui
Traceback (most recent call last):
  File "/home/ivana/.virtualenvs/nengo-dev/bin/nengo_gui", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/ivana/.virtualenvs/nengo-dev/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/home/ivana/.virtualenvs/nengo-dev/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/home/ivana/.virtualenvs/nengo-dev/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ivana/.virtualenvs/nengo-dev/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/ivana/.virtualenvs/nengo-dev/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/ivana/.virtualenvs/nengo-dev/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'numpy>=1.6' distribution was not found and is required by nengo
```
But numpy is installed:
```
(nengo-dev)ivana@CTN05:~/src$ pip freeze | grep numpy
numpy===1.11.0.dev0-0d30809
```
And it works fine if call `nengo_gui` in a simple script:
```python
import nengo
import nengo_gui

model = nengo.Network()
with model:
    a = nengo.Ensemble(100, 1)

nengo_gui.GUI(__file__).start()
```
Other things I've checked and tried:
* Location of `pkg_resources` (on Eric's computer it's in `distribute`):
```
In [2]: pkg_resources.__file__
Out[2]: '/home/ivana/.virtualenvs/nengo-dev/local/lib/python2.7/site-packages/pkg_resources/__init__.pyc'
```

* Uninstalling `nengo`, and installing it again (`python setup.py develop`). In this case it creates an `.eggs` directory in nengo, supposedly ignoring already installed numpy version and getting it's own from pypi (my guess):
```
(nengo-dev)ivana@CTN05:~/src$ python testscript.py 
/home/ivana/phd/workspace/nengo/.eggs/numpy-1.10.1-py2.7-linux-x86_64.egg/numpy/__init__.pyc
```
where a few first lines inf the `testscript.py` are:
```python
import numpy as np
import numpy.random as npr
import time

print np.__file__
```

**Comment by jgosmann** [comment]
@ikajic, can you post the contents of `/home/ivana/.virtualenvs/nengo-dev/bin/nengo_gui`? Did you by any chance install some stuff with `easy_install` and some stuff with `pip`? Was `nengo-dev` created with or without `--system-site-packages`?

**Comment by tbekolay** [comment]
The problem child here is `setuptools`. When you install setuptools, you get the `pkg_resources` package, which defines some functions and classes for getting information about what packages are installed on the system. `setuptools` uses these functions and classes when it's installing things to make sure dependencies are installed, for example.

Nengo uses some things that were added in Numpy 1.6, so we say that we depend on `numpy>=1.6`. When installing Nengo, `setuptools` does something like this (not this of course, but something similar) to determine if Numpy exists, and if so, whether the version is up to date.

```python
from pkg_resources import parse_version
required_version = parse_version('1.6')
try:
    import numpy
    version = numpy.__version__
    good_numpy = parse_version(version) >= required_version
except ImportError:
    good_numpy = False
```

For me, I have NumPy 1.9.2 installed. So the comparison goes like this:

```python
In [13]: pkg_resources.parse_version('1.9.2')
Out[13]: <Version('1.9.2')>

In [14]: parse_version('1.9.2') >= parse_version('1.6')
Out[14]: True
```

Here's what happens with your version:

```python
In [18]: parse_version('1.11.0.dev0-0d30809')
Out[18]: <LegacyVersion('1.11.0.dev0-0d30809')>

In [19]: parse_version('1.11.0.dev0-0d30809') >= parse_version('1.6')
Out[19]: False
```

Long story short, Numpy isn't using properly formed version strings in its development versions, so `pkg_resources` thinks the version you have isn't up to date. That's why when you try to reinstall Nengo, it tries to install Numpy from PyPI.

There are a few ways to remedy the situation. One of them is on our end, which is to write our own `nengo_gui` script; right now we use `setuptools` to automatically generate a script, which is why it does the check to ensure you have Numpy installed before it runs anything (the error message is presumably better than it just failing somewhere in the middle of the program). Personally I would like to avoid doing this, but if it happens a lot, then it's definitely something to consider.

The second is to make sure you're using a stable release version of NumPy rather than a development version. From your version number, I'm guessing that you `git clone`d the NumPy repository, and installed it from source. Assuming that's correct, then I would recommend checking out a stable release tag, and reinstalling Numpy.

Here's how I would do it (the details will change depending on where repositories are, and what version you want, etc):

```bash
pip uninstall numpy  # Might want to try doing this multiple times
cd ~/Code/numpy
git fetch origin
git fetch --tags origin
git checkout v1.10.1  # Gets the repository as of v1.10.1
python setup.py build install
```

**Comment by ikajic** [comment]
Yup, it works with a stable version of NumPy. Thanks Travis!

So, to give you a background on how this happened: I was running simulations from the SPA tutorial (@Seanny123) which were very slow on the machine I'm using. So I got OpenBLAS by doing what [the tutorial](https://hunseblog.wordpress.com/2014/09/15/installing-numpy-and-openblas/) recommends, which is indeed installing NumPy from source.

**Comment by jgosmann** [comment]
Tip: Store your `site.cfg` for the NumPy install as `~/.numpy-site.cfg`. Then NumPy should use OpenBLAS (or whatever you configured) in any install from source including installs with `pip install numpy`. (Not sure if there are situations where `pip install` might fetch precompiled binaries and ignore the `.numpy-site.cfg`, but it was never a problem for me.)

**Comment by ikajic** [comment]
Thanks @jgosmann. So that means if I have the config file where you suggested, I could omit everything below `cd ~/Code/numpy` in Travis' post and just do `pip install numpy`?

**Comment by jgosmann** [comment]
Most likely yes. To check that it acutally works: `pip install numpy` should take some time and probably produce some output for the compiler invocations. Afterwards I would also check that NumPy is indeed using OpenBLAS (the link you posted probably explains how).
